# Generated by Django 3.2.9 on 2021-12-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_entry_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='access',
            field=models.BooleanField(choices=[(True, 'private'), (False, 'public')], default=True),
        ),
    ]
