# Generated by Django 3.2.9 on 2021-12-14 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('learning_logs', '0007_alter_topic_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mygroup'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='access',
            field=models.CharField(choices=[('priv', 'private'), ('pub', 'public'), ('group', 'group')], default='priv', max_length=10),
        ),
    ]
