# Generated by Django 3.2.9 on 2021-12-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('groups', '0002_mygroup_admin'),
    ]

    operations = [
    ]
